var countries =
[
	{ id: "ad", flag: "🇦🇩", names: [ "Andorra" ], zoom: 400 },
	{ id: "ae", flag: "🇦🇪", names: [ "United Arab Emirates", "UAE" ], zoom: 300 },
	{ id: "af", flag: "🇦🇫", names: [ "Afghanistan" ] },
	{ id: "ag", flag: "🇦🇬", names: [ "Antigua and Barbuda" ], zoom: 700 },
	{ id: "al", flag: "🇦🇱", names: [ "Albania" ], zoom: 400 },
	{ id: "am", flag: "🇦🇲", names: [ "Armenia" ], zoom: 400 },
	{ id: "ao", flag: "🇦🇴", names: [ "Angola" ] },
	{ id: "ar", flag: "🇦🇷", names: [ "Argentina" ] },
	{ id: "at", flag: "🇦🇹", names: [ "Austria" ], zoom: 300 },
	{ id: "au", flag: "🇦🇺", names: [ "Australia" ] },
	{ id: "az", flag: "🇦🇿", names: [ "Azerbaijan" ], zoom: 400 },
	{ id: "ba", flag: "🇧🇦", names: [ "Bosnia and Herzegovina" ], zoom: 300 },
	{ id: "bb", flag: "🇧🇧", names: [ "Barbados" ], zoom: 700 },
	{ id: "bd", flag: "🇧🇩", names: [ "Bangladesh" ] },
	{ id: "be", flag: "🇧🇪", names: [ "Belgium" ], zoom: 300 },
	{ id: "bf", flag: "🇧🇫", names: [ "Burkina Faso" ] },
	{ id: "bg", flag: "🇧🇬", names: [ "Bulgaria" ], zoom: 300 },
	{ id: "bh", flag: "🇧🇭", names: [ "Bahrain" ], zoom: 400 },
	{ id: "bi", flag: "🇧🇮", names: [ "Burundi" ], zoom: 300 },
	{ id: "bj", flag: "🇧🇯", names: [ "Benin" ], zoom: 300 },
	{ id: "bn", flag: "🇧🇳", names: [ "Brunei" ], zoom: 400 },
	{ id: "bo", flag: "🇧🇴", names: [ "Bolivia" ] },
	{ id: "br", flag: "🇧🇷", names: [ "Brazil" ] },
	{ id: "bs", flag: "🇧🇸", names: [ "Bahamas" ], zoom: 400 },
	{ id: "bt", flag: "🇧🇹", names: [ "Bhutan" ], zoom: 300 },
	{ id: "bw", flag: "🇧🇼", names: [ "Botswana" ] },
	{ id: "by", flag: "🇧🇾", names: [ "Belarus" ] },
	{ id: "bz", flag: "🇧🇿", names: [ "Belize" ], zoom: 400 },
	{ id: "ca", flag: "🇨🇦", names: [ "Canada" ] },
	{ id: "cd", flag: "🇨🇩", names: [ "Democratic Republic of the Congo", "DR Congo", "D.R. Congo", "D. R. Congo", "D R Congo", "DRC" ] },
	{ id: "cf", flag: "🇨🇫", names: [ "Central African Republic", "CAR" ] },
	{ id: "cg", flag: "🇨🇬", names: [ "Republic of the Congo", "Congo Republic", "Congo" ] },
	{ id: "ch", flag: "🇨🇭", names: [ "Switzerland" ], zoom: 400 },
	{ id: "ci", flag: "🇨🇮", names: [ "Ivory Coast", "Côte d'Ivoire", "Cote d'Ivoire" ] },
	{ id: "cl", flag: "🇨🇱", names: [ "Chile" ] },
	{ id: "cm", flag: "🇨🇲", names: [ "Cameroon" ] },
	{ id: "cn", flag: "🇨🇳", names: [ "China" ] },
	{ id: "co", flag: "🇨🇴", names: [ "Colombia" ] },
	{ id: "cr", flag: "🇨🇷", names: [ "Costa Rica" ], zoom: 400 },
	{ id: "cu", flag: "🇨🇺", names: [ "Cuba" ], zoom: 300 },
	{ id: "cv", flag: "🇨🇻", names: [ "Cape Verde", "Cabo Verde" ], zoom: 400 },
	{ id: "cy", flag: "🇨🇾", names: [ "Cyprus" ], zoom: 400 },
	{ id: "cz", flag: "🇨🇿", names: [ "Czech Republic", "Czechia" ], zoom: 300 },
	{ id: "de", flag: "🇩🇪", names: [ "Germany" ] },
	{ id: "dj", flag: "🇩🇯", names: [ "Djibouti" ], zoom: 400 },
	{ id: "dk", flag: "🇩🇰", names: [ "Denmark" ], zoom: 300 },
	{ id: "dm", flag: "🇩🇲", names: [ "Dominica" ], zoom: 700 },
	{ id: "do", flag: "🇩🇴", names: [ "Dominican Republic" ], zoom: 400 },
	{ id: "dz", flag: "🇩🇿", names: [ "Algeria" ] },
	{ id: "ec", flag: "🇪🇨", names: [ "Ecuador" ] },
	{ id: "ee", flag: "🇪🇪", names: [ "Estonia" ], zoom: 300 },
	{ id: "eg", flag: "🇪🇬", names: [ "Egypt" ] },
	{ id: "er", flag: "🇪🇷", names: [ "Eritrea" ], zoom: 300 },
	{ id: "es", flag: "🇪🇸", names: [ "Spain" ] },
	{ id: "et", flag: "🇪🇹", names: [ "Ethiopia" ] },
	{ id: "fi", flag: "🇫🇮", names: [ "Finland" ] },
	{ id: "fj", flag: "🇫🇯", names: [ "Fiji" ], zoom: 400 },
	{ id: "fm", flag: "🇫🇲", names: [ "Federated States of Micronesia", "Micronesia" ], zoom: 400 },
	{ id: "fr", flag: "🇫🇷", names: [ "France" ] },
	{ id: "ga", flag: "🇬🇦", names: [ "Gabon" ] },
	{ id: "gb", flag: "🇬🇧", names: [ "United Kingdom", "UK" ] },
	{ id: "gd", flag: "🇬🇩", names: [ "Grenada" ], zoom: 700 },
	{ id: "ge", flag: "🇬🇪", names: [ "Georgia" ], zoom: 400 },
	{ id: "gh", flag: "🇬🇭", names: [ "Ghana" ] },
	{ id: "gm", flag: "🇬🇲", names: [ "The Gambia", "Gambia" ], zoom: 400 },
	{ id: "gn", flag: "🇬🇳", names: [ "Guinea" ] },
	{ id: "gq", flag: "🇬🇶", names: [ "Equatorial Guinea" ], zoom: 400 },
	{ id: "gr", flag: "🇬🇷", names: [ "Greece" ], zoom: 400 },
	{ id: "gt", flag: "🇬🇹", names: [ "Guatemala" ], zoom: 400 },
	{ id: "gw", flag: "🇬🇼", names: [ "Guinea-Bissau", "Guinea Bissau" ], zoom: 400 },
	{ id: "gy", flag: "🇬🇾", names: [ "Guyana" ] },
	{ id: "hn", flag: "🇭🇳", names: [ "Honduras" ], zoom: 400 },
	{ id: "hr", flag: "🇭🇷", names: [ "Croatia" ], zoom: 300 },
	{ id: "ht", flag: "🇭🇹", names: [ "Haiti" ], zoom: 400 },
	{ id: "hu", flag: "🇭🇺", names: [ "Hungary" ], zoom: 300 },
	{ id: "id", flag: "🇮🇩", names: [ "Indonesia" ] },
	{ id: "ie", flag: "🇮🇪", names: [ "Ireland", "Republic of Ireland" ], zoom: 300 },
	{ id: "il", flag: "🇮🇱", names: [ "Israel" ], zoom: 500 },
	{ id: "in", flag: "🇮🇳", names: [ "India" ] },
	{ id: "ir", flag: "🇮🇷", names: [ "Iran" ] },
	{ id: "iq", flag: "🇮🇶", names: [ "Iraq" ] },
	{ id: "is", flag: "🇮🇸", names: [ "Iceland" ] },
	{ id: "it", flag: "🇮🇹", names: [ "Italy" ] },
	{ id: "jm", flag: "🇯🇲", names: [ "Jamaica" ], zoom: 400 },
	{ id: "jo", flag: "🇯🇴", names: [ "Jordan" ], zoom: 300 },
	{ id: "jp", flag: "🇯🇵", names: [ "Japan" ] },
	{ id: "ke", flag: "🇰🇪", names: [ "Kenya" ] },
	{ id: "kg", flag: "🇰🇬", names: [ "Kyrgyzstan" ] },
	{ id: "kh", flag: "🇰🇭", names: [ "Cambodia" ] },
	{ id: "ki", flag: "🇰🇮", names: [ "Kiribati" ], zoom: 400 },
	{ id: "km", flag: "🇰🇲", names: [ "Comoros" ], zoom: 400 },
	{ id: "kn", flag: "🇰🇳", names: [ "Saint Kitts and Nevis", "St. Kitts and Nevis", "St Kitts and Nevis" ], zoom: 700 },
	{ id: "kp", flag: "🇰🇵", names: [ "North Korea", "Democratic People's Republic of Korea", "DPRK" ] },
	{ id: "kr", flag: "🇰🇷", names: [ "South Korea", "Republic of Korea" ] },
	{ id: "kw", flag: "🇰🇼", names: [ "Kuwait" ], zoom: 500 },
	{ id: "kz", flag: "🇰🇿", names: [ "Kazakhstan" ] },
	{ id: "la", flag: "🇱🇦", names: [ "Laos" ] },
	{ id: "lb", flag: "🇱🇧", names: [ "Lebanon" ], zoom: 500 },
	{ id: "lc", flag: "🇱🇨", names: [ "Saint Lucia", "St. Lucia", "St Lucia" ], zoom: 700 },
	{ id: "li", flag: "🇱🇮", names: [ "Liechtenstein" ], zoom: 400 },
	{ id: "lk", flag: "🇱🇰", names: [ "Sri Lanka" ] },
	{ id: "lr", flag: "🇱🇷", names: [ "Liberia" ], zoom: 300 },
	{ id: "ls", flag: "🇱🇸", names: [ "Lesotho" ], zoom: 300 },
	{ id: "lt", flag: "🇱🇹", names: [ "Lithuania" ], zoom: 300 },
	{ id: "lu", flag: "🇱🇺", names: [ "Luxembourg" ], zoom: 400 },
	{ id: "lv", flag: "🇱🇻", names: [ "Latvia" ], zoom: 300 },
	{ id: "ly", flag: "🇱🇾", names: [ "Libya" ] },
	{ id: "ma", flag: "🇲🇦", names: [ "Morocco" ] },
	{ id: "mc", flag: "🇲🇨", names: [ "Monaco" ], zoom: 400 },
	{ id: "md", flag: "🇲🇩", names: [ "Moldova" ], zoom: 400 },
	{ id: "me", flag: "🇲🇪", names: [ "Montenegro" ], zoom: 700 },
	{ id: "mg", flag: "🇲🇬", names: [ "Madagascar" ] },
	{ id: "mh", flag: "🇲🇭", names: [ "Marshall Islands" ], zoom: 400 },
	{ id: "mk", flag: "🇲🇰", names: [ "North Macedonia" ], zoom: 400 },
	{ id: "ml", flag: "🇲🇱", names: [ "Mali" ] },
	{ id: "mm", flag: "🇲🇲", names: [ "Myanmar", "Burma" ] },
	{ id: "mn", flag: "🇲🇳", names: [ "Mongolia" ] },
	{ id: "mr", flag: "🇲🇷", names: [ "Mauritania" ] },
	{ id: "mt", flag: "🇲🇹", names: [ "Malta" ], zoom: 400 },
	{ id: "mu", flag: "🇲🇺", names: [ "Mauritius" ], zoom: 400 },
	{ id: "mv", flag: "🇲🇻", names: [ "Maldives" ], zoom: 300 },
	{ id: "mw", flag: "🇲🇼", names: [ "Malawi" ], zoom: 300 },
	{ id: "mx", flag: "🇲🇽", names: [ "Mexico" ] },
	{ id: "my", flag: "🇲🇾", names: [ "Malaysia" ] },
	{ id: "mz", flag: "🇲🇿", names: [ "Mozambique" ] },
	{ id: "na", flag: "🇳🇦", names: [ "Namibia" ] },
	{ id: "ne", flag: "🇳🇪", names: [ "Niger" ] },
	{ id: "ng", flag: "🇳🇬", names: [ "Nigeria" ] },
	{ id: "ni", flag: "🇳🇮", names: [ "Nicaragua" ], zoom: 400 },
	{ id: "nl", flag: "🇳🇱", names: [ "Netherlands", "The Netherlands" ], zoom: 300 },
	{ id: "no", flag: "🇳🇴", names: [ "Norway" ] },
	{ id: "np", flag: "🇳🇵", names: [ "Nepal" ], zoom: 300 },
	{ id: "nr", flag: "🇳🇷", names: [ "Nauru" ] },
	{ id: "nz", flag: "🇳🇿", names: [ "New Zealand" ] },
	{ id: "om", flag: "🇴🇲", names: [ "Oman" ] },
	{ id: "pa", flag: "🇵🇦", names: [ "Panama" ], zoom: 400 },
	{ id: "pe", flag: "🇵🇪", names: [ "Peru" ] },
	{ id: "pg", flag: "🇵🇬", names: [ "Papua New Guinea", "PNG" ] },
	{ id: "ph", flag: "🇵🇭", names: [ "Philippines" ] },
	{ id: "pl", flag: "🇵🇱", names: [ "Poland" ], zoom: 300 },
	{ id: "pk", flag: "🇵🇰", names: [ "Pakistan" ] },
	{ id: "ps", flag: "🇵🇸", names: [ "Palestine" ], zoom: 600 },
	{ id: "pt", flag: "🇵🇹", names: [ "Portugal" ], zoom: 300 },
	{ id: "pw", flag: "🇵🇼", names: [ "Palau" ], zoom: 400 },
	{ id: "py", flag: "🇵🇾", names: [ "Paraguay" ] },
	{ id: "qa", flag: "🇶🇦", names: [ "Qatar" ], zoom: 400 },
	{ id: "ro", flag: "🇷🇴", names: [ "Romania" ], zoom: 300 },
	{ id: "rs", flag: "🇷🇸", names: [ "Serbia" ], zoom: 300 },
	{ id: "ru", flag: "🇷🇺", names: [ "Russia", "Russian Federation" ] },
	{ id: "rw", flag: "🇷🇼", names: [ "Rwanda" ], zoom: 300 },
	{ id: "sa", flag: "🇸🇦", names: [ "Saudi Arabia" ] },
	{ id: "sb", flag: "🇸🇧", names: [ "Solomon Islands" ], zoom: 400 },
	{ id: "sc", flag: "🇸🇨", names: [ "Seychelles" ], zoom: 400 },
	{ id: "sd", flag: "🇸🇩", names: [ "Sudan" ] },
	{ id: "se", flag: "🇸🇪", names: [ "Sweden" ] },
	{ id: "sg", flag: "🇸🇬", names: [ "Singapore" ], zoom: 400 },
	{ id: "si", flag: "🇸🇮", names: [ "Slovenia" ], zoom: 400 },
	{ id: "sk", flag: "🇸🇰", names: [ "Slovakia" ], zoom: 300 },
	{ id: "sl", flag: "🇸🇱", names: [ "Sierra Leone" ], zoom: 300 },
	{ id: "sm", flag: "🇸🇲", names: [ "San Marino" ], zoom: 700 },
	{ id: "sn", flag: "🇸🇳", names: [ "Senegal" ] },
	{ id: "so", flag: "🇸🇴", names: [ "Somalia" ] },
	{ id: "sr", flag: "🇸🇷", names: [ "Suriname" ] },
	{ id: "ss", flag: "🇸🇸", names: [ "South Sudan" ] },
	{ id: "st", flag: "🇸🇹", names: [ "São Tomé and Príncipe", "Sao Tome and Principe" ], zoom: 400 },
	{ id: "sv", flag: "🇸🇻", names: [ "El Salvador" ], zoom: 400 },
	{ id: "sy", flag: "🇸🇾", names: [ "Syria" ] },
	{ id: "sz", flag: "🇸🇿", names: [ "Eswatini", "Swaziland" ], zoom: 300 },
	{ id: "td", flag: "🇹🇩", names: [ "Chad" ] },
	{ id: "tg", flag: "🇹🇬", names: [ "Togo" ], zoom: 300 },
	{ id: "th", flag: "🇹🇭", names: [ "Thailand" ] },
	{ id: "tj", flag: "🇹🇯", names: [ "Tajikistan" ] },
	{ id: "tl", flag: "🇹🇱", names: [ "East Timor", "Timor-Leste", "Timor Leste" ], zoom: 400 },
	{ id: "tm", flag: "🇹🇲", names: [ "Turkmenistan" ] },
	{ id: "tn", flag: "🇹🇳", names: [ "Tunisia" ] },
	{ id: "to", flag: "🇹🇴", names: [ "Tonga" ], zoom: 400 },
	{ id: "tr", flag: "🇹🇷", names: [ "Turkey", "Türkiye", "Turkiye" ] },
	{ id: "tt", flag: "🇹🇹", names: [ "Trinidad and Tobago" ], zoom: 700 },
	{ id: "tv", flag: "🇹🇻", names: [ "Tuvalu" ], zoom: 400 },
	{ id: "tz", flag: "🇹🇿", names: [ "Tanzania" ] },
	{ id: "ua", flag: "🇺🇦", names: [ "Ukraine" ] },
	{ id: "ug", flag: "🇺🇬", names: [ "Uganda" ] },
	{ id: "us", flag: "🇺🇸", names: [ "United States of America", "United States", "USA", "US" ] },
	{ id: "uy", flag: "🇺🇾", names: [ "Uruguay" ] },
	{ id: "uz", flag: "🇺🇿", names: [ "Uzbekistan" ] },
	{ id: "va", flag: "🇻🇦", names: [ "Vatican City", "Vatican" ], zoom: 700 },
	{ id: "vc", flag: "🇻🇨", names: [ "Saint Vincent and the Grenadines", "St. Vincent and the Grenadines", "St Vincent and the Grenadines" ], zoom: 700 },
	{ id: "ve", flag: "🇻🇪", names: [ "Venezuela" ] },
	{ id: "vn", flag: "🇻🇳", names: [ "Vietnam" ] },
	{ id: "vu", flag: "🇻🇺", names: [ "Vanuatu" ], zoom: 400 },
	{ id: "ws", flag: "🇼🇸", names: [ "Samoa", "Western Samoa" ], zoom: 400 },
	{ id: "xk", flag: "🇽🇰", names: [ "Kosovo" ], zoom: 700 },
	{ id: "ye", flag: "🇾🇪", names: [ "Yemen" ] },
	{ id: "za", flag: "🇿🇦", names: [ "South Africa" ] },
	{ id: "zm", flag: "🇿🇲", names: [ "Zambia" ] },
	{ id: "zw", flag: "🇿🇼", names: [ "Zimbabwe" ] },
]
;
